---

- hosts: localhost
  connection: local
  become: true

  vars_prompt:
    - name: rpi_model
      prompt: Enter Raspberry Pi model
      private: no
    - name: rpi_arch
      prompt: Enter kernel architecture
      private: no
    # - name: build_dir
    #   prompt: Enter temporary directory in which to build kernel
    #   private: no

  vars_files:
    - variables/kernel.yml

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes

  tasks:
    - include: tasks/packages.yml
    - include: tasks/kernel-build.yml

