---

- name: Install required dependencies
  apt:
    name:
      - git
      - bc
      - bison
      - flex
      - libssl-dev
      - make
      - libc6-dev
      - libncurses5-dev
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - packages

- name: Install toolchain
  apt:
    name: "{{ toolchain[rpi_arch] }}"
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - packages
